# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-21 17:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Workout_type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ccals', models.IntegerField(verbose_name='\u043a\u043a\u0430\u043b/\u0447\u0430\u0441')),
            ],
        ),
        migrations.RenameModel(
            old_name='Train',
            new_name='Workout',
        ),
        migrations.AddField(
            model_name='workout_type',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='page.Workout'),
        ),
    ]
